export const LOCATION_CATALOG: Record<string, string[]> = {
  India: [
    "Ahmedabad",
    "Bengaluru",
    "Chennai",
    "Delhi",
    "Hyderabad",
    "Jaipur",
    "Kolkata",
    "Lucknow",
    "Mumbai",
    "Pune",
    "Surat",
  ],
  "United States": [
    "Atlanta",
    "Austin",
    "Boston",
    "Chicago",
    "Dallas",
    "Los Angeles",
    "Miami",
    "New York",
    "San Francisco",
    "Seattle",
  ],
  "United Kingdom": [
    "Birmingham",
    "Bristol",
    "Edinburgh",
    "Glasgow",
    "Leeds",
    "Liverpool",
    "London",
    "Manchester",
  ],
  Canada: ["Calgary", "Edmonton", "Montreal", "Ottawa", "Toronto", "Vancouver"],
  Australia: ["Adelaide", "Brisbane", "Canberra", "Melbourne", "Perth", "Sydney"],
  Germany: ["Berlin", "Cologne", "Frankfurt", "Hamburg", "Munich", "Stuttgart"],
  France: ["Bordeaux", "Lille", "Lyon", "Marseille", "Nice", "Paris", "Toulouse"],
  Singapore: ["Singapore"],
  "United Arab Emirates": ["Abu Dhabi", "Dubai", "Sharjah"],
  Japan: ["Fukuoka", "Nagoya", "Osaka", "Sapporo", "Tokyo", "Yokohama"],
  Brazil: ["Brasilia", "Rio de Janeiro", "Sao Paulo"],
  "South Africa": ["Cape Town", "Durban", "Johannesburg"],
  "Saudi Arabia": ["Dammam", "Jeddah", "Mecca", "Medina", "Riyadh"],
  Mexico: ["Cancun", "Guadalajara", "Mexico City", "Monterrey", "Puebla"],
  Spain: ["Barcelona", "Bilbao", "Madrid", "Malaga", "Seville", "Valencia"],
  Italy: ["Bologna", "Florence", "Milan", "Naples", "Rome", "Turin"],
  Netherlands: ["Amsterdam", "Eindhoven", "Rotterdam", "The Hague", "Utrecht"],
  Sweden: ["Gothenburg", "Malmo", "Stockholm", "Uppsala"],
  Norway: ["Bergen", "Oslo", "Stavanger", "Trondheim"],
  Denmark: ["Aarhus", "Copenhagen", "Odense"],
  Switzerland: ["Basel", "Bern", "Geneva", "Lausanne", "Zurich"],
  "New Zealand": ["Auckland", "Christchurch", "Hamilton", "Wellington"],
  Indonesia: ["Bandung", "Jakarta", "Medan", "Surabaya", "Yogyakarta"],
  Malaysia: ["George Town", "Johor Bahru", "Kuala Lumpur", "Kuching"],
  Thailand: ["Bangkok", "Chiang Mai", "Phuket", "Pattaya"],
  Vietnam: ["Da Nang", "Hanoi", "Ho Chi Minh City", "Nha Trang"],
  Philippines: ["Cebu City", "Davao City", "Manila", "Quezon City"],
  Nigeria: ["Abuja", "Ibadan", "Kano", "Lagos", "Port Harcourt"],
  Kenya: ["Eldoret", "Kisumu", "Mombasa", "Nairobi"],
  Egypt: ["Alexandria", "Cairo", "Giza", "Sharm El Sheikh"],
  Turkey: ["Ankara", "Antalya", "Bursa", "Istanbul", "Izmir"],
  "South Korea": ["Busan", "Daegu", "Daejeon", "Incheon", "Seoul"],
  Argentina: ["Buenos Aires", "Cordoba", "Mendoza", "Rosario"],
  Chile: ["Antofagasta", "Santiago", "Valparaiso"],
  Poland: ["Gdansk", "Krakow", "Lodz", "Poznan", "Warsaw", "Wroclaw"],
  Belgium: ["Antwerp", "Brussels", "Ghent", "Liege"],
  Portugal: ["Braga", "Faro", "Lisbon", "Porto"],
  Ireland: ["Cork", "Dublin", "Galway", "Limerick"],
  Austria: ["Graz", "Innsbruck", "Linz", "Salzburg", "Vienna"],
  Qatar: ["Al Khor", "Al Wakrah", "Doha", "Lusail"],
};

export function getCountryList() {
  return Object.keys(LOCATION_CATALOG).sort((a, b) => a.localeCompare(b));
}

export function getCitiesByCountry(country: string) {
  return [...(LOCATION_CATALOG[country] ?? [])].sort((a, b) => a.localeCompare(b));
}
