import { BusinessProfile } from "@/types/domain";

export const featuredBusinesses: BusinessProfile[] = [
  {
    id: "b_01",
    ownerUid: "u_business_01",
    businessName: "Aster Electronics",
    slug: "aster-electronics",
    mode: "online",
    stage: "running",
    category: "Consumer Electronics",
    yearsInField: 6,
    supportEmail: "support@asterelectronics.example",
    supportPhone: "+91-90000-10001",
    address: "M.G. Road 1",
    city: "Bengaluru",
    country: "India",
    website: "https://asterelectronics.example",
    status: "approved",
    certificateId: "cert_01",
    trustScore: 92,
    followersCount: 1934,
    isPartnershipOpen: true,
    partnershipCategory: "Retail Expansion",
    partnershipAmountMin: 200000,
    partnershipAmountMax: 700000,
    createdAt: "2026-01-11T09:30:00.000Z",
    updatedAt: "2026-03-21T16:30:00.000Z",
  },
  {
    id: "b_02",
    ownerUid: "u_business_02",
    businessName: "Stoneleaf Furnitures",
    slug: "stoneleaf-furnitures",
    mode: "offline",
    stage: "running",
    category: "Furniture",
    yearsInField: 11,
    supportEmail: "care@stoneleaf.example",
    supportPhone: "+91-90000-10002",
    address: "Industrial Layout Phase 2",
    city: "Hyderabad",
    country: "India",
    status: "approved",
    certificateId: "cert_02",
    trustScore: 95,
    followersCount: 812,
    isPartnershipOpen: false,
    createdAt: "2025-07-18T09:30:00.000Z",
    updatedAt: "2026-03-17T12:10:00.000Z",
  },
  {
    id: "b_03",
    ownerUid: "u_business_03",
    businessName: "SignalSpark Tools",
    slug: "signalspark-tools",
    mode: "online",
    stage: "running",
    category: "Digital Tools",
    yearsInField: 3,
    supportEmail: "hello@signalspark.example",
    supportPhone: "+91-90000-10003",
    address: "Cyber Towers",
    city: "Pune",
    country: "India",
    website: "https://signalspark.example",
    status: "approved",
    certificateId: "cert_03",
    trustScore: 88,
    followersCount: 2460,
    isPartnershipOpen: true,
    partnershipCategory: "SaaS Integrations",
    partnershipAmountMin: 50000,
    partnershipAmountMax: 250000,
    createdAt: "2025-12-04T09:30:00.000Z",
    updatedAt: "2026-03-26T18:42:00.000Z",
  },
  {
    id: "b_04",
    ownerUid: "u_business_04",
    businessName: "Urban Fresh Markets",
    slug: "urban-fresh-markets",
    mode: "offline",
    stage: "running",
    category: "Food & Grocery",
    yearsInField: 8,
    supportEmail: "support@urbanfresh.example",
    supportPhone: "+91-90000-10004",
    address: "Lake View Avenue",
    city: "Chennai",
    country: "India",
    status: "pending",
    trustScore: 79,
    followersCount: 541,
    isPartnershipOpen: false,
    createdAt: "2026-02-02T09:30:00.000Z",
    updatedAt: "2026-03-22T10:22:00.000Z",
  },
];
