import {
  addDoc,
  collection,
  doc,
  getDoc,
  getDocs,
  limit,
  orderBy,
  query,
  serverTimestamp,
  setDoc,
  updateDoc,
  where,
} from "firebase/firestore";
import { db } from "@/lib/firebase/client";
import { OrderRecord, SupportTicketRecord } from "@/lib/firebase/repositories";

type TimestampValue = { toDate: () => Date };

function toISODate(value: unknown) {
  const maybeTimestamp = value as TimestampValue | undefined;
  if (maybeTimestamp && typeof maybeTimestamp.toDate === "function") {
    return maybeTimestamp.toDate().toISOString();
  }
  if (typeof value === "string" && value.trim()) return value;
  return new Date().toISOString();
}

function getDb() {
  if (!db) {
    throw new Error("Firebase is not configured. Add NEXT_PUBLIC_FIREBASE_* values.");
  }
  return db;
}

function normalizeSlug(text: string) {
  return text
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "");
}

function randomFragment(length = 8) {
  return Math.random().toString(36).slice(2, 2 + length);
}

type BasicBusinessRecord = {
  id: string;
  slug: string;
  ownerUid: string;
  businessName: string;
  status: string;
};

function mapBasicBusiness(snapshotId: string, data: Record<string, unknown>): BasicBusinessRecord {
  return {
    id: snapshotId,
    slug: String(data.slug ?? normalizeSlug(String(data.businessName ?? snapshotId))),
    ownerUid: String(data.ownerUid ?? ""),
    businessName: String(data.businessName ?? "Business"),
    status: String(data.status ?? "pending"),
  };
}

async function fetchPrimaryBusinessByOwner(ownerUid: string) {
  const database = getDb();
  const approvedSnapshots = await getDocs(
    query(
      collection(database, "businessApplications"),
      where("ownerUid", "==", ownerUid),
      where("status", "==", "approved"),
      limit(20),
    ),
  );
  if (!approvedSnapshots.empty) {
    const row = approvedSnapshots.docs[0];
    return mapBasicBusiness(row.id, row.data());
  }
  const fallbackSnapshots = await getDocs(
    query(
      collection(database, "businessApplications"),
      where("ownerUid", "==", ownerUid),
      limit(20),
    ),
  );
  if (fallbackSnapshots.empty) return null;
  const row = fallbackSnapshots.docs[0];
  return mapBasicBusiness(row.id, row.data());
}

async function fetchBusinessBySlug(slug: string) {
  const cleanSlug = normalizeSlug(slug);
  if (!cleanSlug) return null;
  const database = getDb();
  const snapshots = await getDocs(
    query(
      collection(database, "businessApplications"),
      where("slug", "==", cleanSlug),
      limit(1),
    ),
  );
  const row = snapshots.docs[0];
  return row ? mapBasicBusiness(row.id, row.data()) : null;
}

function mapSupportTicket(snapshotId: string, data: Record<string, unknown>) {
  return {
    id: snapshotId,
    customerUid: String(data.customerUid ?? ""),
    customerName: String(data.customerName ?? "Customer"),
    customerEmail: String(data.customerEmail ?? ""),
    businessId: data.businessId ? String(data.businessId) : undefined,
    businessSlug: data.businessSlug ? String(data.businessSlug) : undefined,
    businessName: String(data.businessName ?? ""),
    orderReference: data.orderReference ? String(data.orderReference) : undefined,
    title: String(data.title ?? ""),
    description: String(data.description ?? ""),
    priority: (data.priority as SupportTicketRecord["priority"]) ?? "medium",
    expectedOutcome: String(data.expectedOutcome ?? ""),
    evidenceUrls: Array.isArray(data.evidenceUrls)
      ? (data.evidenceUrls as unknown[]).map((entry) => String(entry))
      : [],
    sourceType: data.sourceType
      ? (String(data.sourceType) as SupportTicketRecord["sourceType"])
      : undefined,
    sourceId: data.sourceId ? String(data.sourceId) : undefined,
    autoGenerated: Boolean(data.autoGenerated),
    status: (data.status as SupportTicketRecord["status"]) ?? "open",
    participantUids: Array.isArray(data.participantUids)
      ? (data.participantUids as unknown[]).map((entry) => String(entry))
      : [],
    escalationCount: Number(data.escalationCount ?? 0),
    reopenedCount: Number(data.reopenedCount ?? 0),
    resolutionReason: data.resolutionReason ? String(data.resolutionReason) : undefined,
    resolvedBy: data.resolvedBy ? String(data.resolvedBy) : undefined,
    resolvedAt: data.resolvedAt ? toISODate(data.resolvedAt) : undefined,
    updatedAt: toISODate(data.updatedAt),
    createdAt: toISODate(data.createdAt),
  } satisfies SupportTicketRecord;
}

function mapOrder(snapshotId: string, data: Record<string, unknown>) {
  return {
    id: snapshotId,
    productId: String(data.productId ?? ""),
    productSlug: String(data.productSlug ?? ""),
    productTitle: String(data.productTitle ?? ""),
    businessOwnerUid: String(data.businessOwnerUid ?? ""),
    businessOwnerName: String(data.businessOwnerName ?? "Business"),
    customerUid: String(data.customerUid ?? ""),
    customerName: String(data.customerName ?? "Customer"),
    customerEmail: String(data.customerEmail ?? ""),
    amount: Number(data.amount ?? 0),
    pricingPlanKey: data.pricingPlanKey ? String(data.pricingPlanKey) : undefined,
    pricingPlanName: data.pricingPlanName ? String(data.pricingPlanName) : undefined,
    pricingPlanBillingCycle: data.pricingPlanBillingCycle
      ? String(data.pricingPlanBillingCycle)
      : undefined,
    status: String(data.status ?? "paid"),
    noRefund: Boolean(data.noRefund),
    escrowReleaseAt: String(data.escrowReleaseAt ?? new Date().toISOString()),
    refundDeadlineAt: String(data.refundDeadlineAt ?? new Date().toISOString()),
    refundReason: data.refundReason ? String(data.refundReason) : undefined,
    refundEvidenceUrls: Array.isArray(data.refundEvidenceUrls)
      ? (data.refundEvidenceUrls as unknown[]).map((entry) => String(entry))
      : [],
    refundTicketId: data.refundTicketId ? String(data.refundTicketId) : undefined,
    createdAt: toISODate(data.createdAt),
    updatedAt: toISODate(data.updatedAt),
  } as unknown as OrderRecord;
}

export type VerificationTierKey = "basic" | "advanced" | "pro_escrow";
export type VerificationTierStatus = "pending" | "approved" | "rejected";

export interface BusinessVerificationTierRecord {
  id: string;
  businessId: string;
  businessSlug: string;
  businessName: string;
  ownerUid: string;
  requestedTier: VerificationTierKey;
  currentTier: VerificationTierKey;
  status: VerificationTierStatus;
  requestedNote?: string;
  adminReason?: string;
  reviewedByUid?: string;
  reviewedByName?: string;
  requestedAt: string;
  updatedAt: string;
}

function mapVerificationTier(snapshotId: string, data: Record<string, unknown>) {
  const requestedTier = String(data.requestedTier ?? "basic");
  const currentTier = String(data.currentTier ?? "basic");
  const toTier = (value: string): VerificationTierKey =>
    value === "advanced" || value === "pro_escrow" ? value : "basic";
  const status = String(data.status ?? "pending");
  return {
    id: snapshotId,
    businessId: String(data.businessId ?? ""),
    businessSlug: String(data.businessSlug ?? ""),
    businessName: String(data.businessName ?? "Business"),
    ownerUid: String(data.ownerUid ?? ""),
    requestedTier: toTier(requestedTier),
    currentTier: toTier(currentTier),
    status: status === "approved" || status === "rejected" ? status : "pending",
    requestedNote: data.requestedNote ? String(data.requestedNote) : undefined,
    adminReason: data.adminReason ? String(data.adminReason) : undefined,
    reviewedByUid: data.reviewedByUid ? String(data.reviewedByUid) : undefined,
    reviewedByName: data.reviewedByName ? String(data.reviewedByName) : undefined,
    requestedAt: toISODate(data.requestedAt),
    updatedAt: toISODate(data.updatedAt),
  } satisfies BusinessVerificationTierRecord;
}

export async function fetchBusinessVerificationTierByOwner(ownerUid: string) {
  const business = await fetchPrimaryBusinessByOwner(ownerUid);
  if (!business) return null;
  const database = getDb();
  const snapshot = await getDoc(doc(database, "businessVerificationTiers", business.id));
  if (!snapshot.exists()) {
    return {
      id: business.id,
      businessId: business.id,
      businessSlug: business.slug,
      businessName: business.businessName,
      ownerUid,
      requestedTier: "basic",
      currentTier: "basic",
      status: "approved",
      requestedAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    } satisfies BusinessVerificationTierRecord;
  }
  return mapVerificationTier(snapshot.id, snapshot.data());
}

export async function fetchBusinessVerificationTierBySlug(slug: string) {
  const business = await fetchBusinessBySlug(slug);
  if (!business) return null;
  const database = getDb();
  const snapshot = await getDoc(doc(database, "businessVerificationTiers", business.id));
  if (!snapshot.exists()) return null;
  return mapVerificationTier(snapshot.id, snapshot.data());
}

export async function requestBusinessVerificationTier(payload: {
  ownerUid: string;
  requestedTier: VerificationTierKey;
  note?: string;
}) {
  const business = await fetchPrimaryBusinessByOwner(payload.ownerUid);
  if (!business) throw new Error("Business profile not found.");
  const database = getDb();
  const ref = doc(database, "businessVerificationTiers", business.id);
  const existing = await getDoc(ref);
  const current = existing.exists()
    ? mapVerificationTier(existing.id, existing.data())
    : null;
  await setDoc(
    ref,
    {
      businessId: business.id,
      businessSlug: business.slug,
      businessName: business.businessName,
      ownerUid: payload.ownerUid,
      requestedTier: payload.requestedTier,
      currentTier: current?.currentTier ?? "basic",
      status: "pending",
      requestedNote: payload.note?.trim() || null,
      requestedAt: serverTimestamp(),
      updatedAt: serverTimestamp(),
    },
    { merge: true },
  );
}

export async function fetchPendingTierRequests(limitRows = 120) {
  const database = getDb();
  const snapshots = await getDocs(
    query(
      collection(database, "businessVerificationTiers"),
      where("status", "==", "pending"),
      orderBy("requestedAt", "desc"),
      limit(Math.max(1, Math.min(300, Math.round(limitRows)))),
    ),
  );
  return snapshots.docs.map((snapshot) => mapVerificationTier(snapshot.id, snapshot.data()));
}

export async function adminReviewTierRequest(payload: {
  businessId: string;
  decision: "approved" | "rejected";
  adminUid: string;
  adminName: string;
  reason?: string;
}) {
  const database = getDb();
  const ref = doc(database, "businessVerificationTiers", payload.businessId);
  const snapshot = await getDoc(ref);
  if (!snapshot.exists()) throw new Error("Tier request not found.");
  const row = mapVerificationTier(snapshot.id, snapshot.data());
  await updateDoc(ref, {
    status: payload.decision,
    currentTier: payload.decision === "approved" ? row.requestedTier : row.currentTier,
    adminReason: payload.reason?.trim() || null,
    reviewedByUid: payload.adminUid,
    reviewedByName: payload.adminName,
    updatedAt: serverTimestamp(),
  });
}

export type TrustTimelineEventType =
  | "verification"
  | "compliance"
  | "refund_resolution"
  | "certificate"
  | "milestone";

export interface TrustTimelineEventRecord {
  id: string;
  businessId: string;
  businessSlug: string;
  businessName: string;
  ownerUid: string;
  eventType: TrustTimelineEventType;
  title: string;
  detail: string;
  visibility: "public" | "internal";
  createdByUid: string;
  createdByName: string;
  createdAt: string;
  updatedAt: string;
}

function mapTrustTimelineEvent(snapshotId: string, data: Record<string, unknown>) {
  const rawType = String(data.eventType ?? "milestone");
  const eventType: TrustTimelineEventType =
    rawType === "verification" ||
    rawType === "compliance" ||
    rawType === "refund_resolution" ||
    rawType === "certificate"
      ? rawType
      : "milestone";
  const visibility = data.visibility === "internal" ? "internal" : "public";
  return {
    id: snapshotId,
    businessId: String(data.businessId ?? ""),
    businessSlug: String(data.businessSlug ?? ""),
    businessName: String(data.businessName ?? "Business"),
    ownerUid: String(data.ownerUid ?? ""),
    eventType,
    title: String(data.title ?? ""),
    detail: String(data.detail ?? ""),
    visibility,
    createdByUid: String(data.createdByUid ?? ""),
    createdByName: String(data.createdByName ?? "System"),
    createdAt: toISODate(data.createdAt),
    updatedAt: toISODate(data.updatedAt),
  } satisfies TrustTimelineEventRecord;
}

export async function createBusinessTrustTimelineEvent(payload: {
  ownerUid: string;
  createdByUid: string;
  createdByName: string;
  eventType: TrustTimelineEventType;
  title: string;
  detail: string;
  visibility?: "public" | "internal";
}) {
  const business = await fetchPrimaryBusinessByOwner(payload.ownerUid);
  if (!business) throw new Error("Business profile not found.");
  const database = getDb();
  await addDoc(collection(database, "trustTimelineEvents"), {
    businessId: business.id,
    businessSlug: business.slug,
    businessName: business.businessName,
    ownerUid: payload.ownerUid,
    eventType: payload.eventType,
    title: payload.title.trim(),
    detail: payload.detail.trim(),
    visibility: payload.visibility ?? "public",
    createdByUid: payload.createdByUid,
    createdByName: payload.createdByName,
    createdAt: serverTimestamp(),
    updatedAt: serverTimestamp(),
  });
}

export async function fetchBusinessTrustTimelineByOwner(ownerUid: string, limitRows = 80) {
  const database = getDb();
  const snapshots = await getDocs(
    query(
      collection(database, "trustTimelineEvents"),
      where("ownerUid", "==", ownerUid),
      orderBy("createdAt", "desc"),
      limit(Math.max(1, Math.min(200, Math.round(limitRows)))),
    ),
  );
  return snapshots.docs.map((snapshot) => mapTrustTimelineEvent(snapshot.id, snapshot.data()));
}

export async function fetchPublicTrustTimelineByBusinessSlug(slug: string, limitRows = 40) {
  const cleanSlug = normalizeSlug(slug);
  if (!cleanSlug) return [];
  const database = getDb();
  const snapshots = await getDocs(
    query(
      collection(database, "trustTimelineEvents"),
      where("businessSlug", "==", cleanSlug),
      where("visibility", "==", "public"),
      orderBy("createdAt", "desc"),
      limit(Math.max(1, Math.min(200, Math.round(limitRows)))),
    ),
  );
  return snapshots.docs.map((snapshot) => mapTrustTimelineEvent(snapshot.id, snapshot.data()));
}

export interface DisputeSlaPolicyRecord {
  id: string;
  firstResponseHours: number;
  adminEscalationHours: number;
  autoRefundHours: number;
  updatedByUid?: string;
  updatedAt: string;
}

export interface DisputeSlaBreachRecord {
  id: string;
  ticketId: string;
  businessName: string;
  customerEmail: string;
  status: string;
  ageHours: number;
  breachStage: "none" | "response_due" | "admin_escalation_due" | "auto_refund_due";
  ownerUid?: string;
  createdAt: string;
}

function mapDisputeSlaPolicy(snapshotId: string, data: Record<string, unknown>) {
  return {
    id: snapshotId,
    firstResponseHours: Math.max(1, Number(data.firstResponseHours ?? 24)),
    adminEscalationHours: Math.max(1, Number(data.adminEscalationHours ?? 48)),
    autoRefundHours: Math.max(1, Number(data.autoRefundHours ?? 96)),
    updatedByUid: data.updatedByUid ? String(data.updatedByUid) : undefined,
    updatedAt: toISODate(data.updatedAt),
  } satisfies DisputeSlaPolicyRecord;
}

function mapDisputeSlaBreach(snapshotId: string, data: Record<string, unknown>) {
  const rawStage = String(data.breachStage ?? "none");
  const breachStage =
    rawStage === "response_due" ||
    rawStage === "admin_escalation_due" ||
    rawStage === "auto_refund_due"
      ? rawStage
      : "none";
  return {
    id: snapshotId,
    ticketId: String(data.ticketId ?? ""),
    businessName: String(data.businessName ?? ""),
    customerEmail: String(data.customerEmail ?? ""),
    status: String(data.status ?? "open"),
    ageHours: Number(data.ageHours ?? 0),
    breachStage,
    ownerUid: data.ownerUid ? String(data.ownerUid) : undefined,
    createdAt: toISODate(data.createdAt),
  } satisfies DisputeSlaBreachRecord;
}

export async function fetchDisputeSlaPolicy() {
  const database = getDb();
  const snapshot = await getDoc(doc(database, "platformSettings", "disputeSla"));
  if (!snapshot.exists()) {
    return {
      id: "disputeSla",
      firstResponseHours: 24,
      adminEscalationHours: 48,
      autoRefundHours: 96,
      updatedAt: new Date().toISOString(),
    } satisfies DisputeSlaPolicyRecord;
  }
  return mapDisputeSlaPolicy(snapshot.id, snapshot.data() as Record<string, unknown>);
}

export async function updateDisputeSlaPolicy(payload: {
  adminUid: string;
  firstResponseHours: number;
  adminEscalationHours: number;
  autoRefundHours: number;
}) {
  const database = getDb();
  await setDoc(
    doc(database, "platformSettings", "disputeSla"),
    {
      firstResponseHours: Math.max(1, Math.round(payload.firstResponseHours)),
      adminEscalationHours: Math.max(1, Math.round(payload.adminEscalationHours)),
      autoRefundHours: Math.max(1, Math.round(payload.autoRefundHours)),
      updatedByUid: payload.adminUid,
      updatedAt: serverTimestamp(),
    },
    { merge: true },
  );
}

export async function fetchOpenDisputeTickets(limitRows = 120) {
  const database = getDb();
  const snapshots = await getDocs(
    query(
      collection(database, "supportTickets"),
      where("status", "in", ["open", "in_discussion", "awaiting_admin"]),
      orderBy("createdAt", "desc"),
      limit(Math.max(1, Math.min(300, Math.round(limitRows)))),
    ),
  );
  return snapshots.docs.map((snapshot) => mapSupportTicket(snapshot.id, snapshot.data()));
}

export async function evaluateDisputeSlaBreaches(adminUid: string, limitRows = 160) {
  const database = getDb();
  const policy = await fetchDisputeSlaPolicy();
  const tickets = await fetchOpenDisputeTickets(limitRows);
  const now = Date.now();
  const breaches: DisputeSlaBreachRecord[] = [];
  for (const ticket of tickets) {
    const ageHours = Math.max(
      0,
      Number(((now - Date.parse(ticket.createdAt)) / (60 * 60 * 1000)).toFixed(1)),
    );
    let breachStage: DisputeSlaBreachRecord["breachStage"] = "none";
    if (ageHours >= policy.autoRefundHours) {
      breachStage = "auto_refund_due";
    } else if (ageHours >= policy.adminEscalationHours) {
      breachStage = "admin_escalation_due";
    } else if (ageHours >= policy.firstResponseHours) {
      breachStage = "response_due";
    }
    if (breachStage === "none") continue;
    const breachRef = doc(database, "disputeSlaBreaches", ticket.id);
    await setDoc(
      breachRef,
      {
        ticketId: ticket.id,
        businessName: ticket.businessName,
        customerEmail: ticket.customerEmail,
        ownerUid: ticket.participantUids.find((uid) => uid !== ticket.customerUid) ?? null,
        status: ticket.status,
        ageHours,
        breachStage,
        reviewedByUid: adminUid,
        createdAt: serverTimestamp(),
      },
      { merge: true },
    );
    breaches.push({
      id: ticket.id,
      ticketId: ticket.id,
      businessName: ticket.businessName,
      customerEmail: ticket.customerEmail,
      status: ticket.status,
      ageHours,
      breachStage,
      ownerUid: ticket.participantUids.find((uid) => uid !== ticket.customerUid),
      createdAt: new Date().toISOString(),
    });
  }
  return breaches;
}

export async function fetchDisputeSlaBreaches(limitRows = 120) {
  const database = getDb();
  const snapshots = await getDocs(
    query(
      collection(database, "disputeSlaBreaches"),
      orderBy("createdAt", "desc"),
      limit(Math.max(1, Math.min(300, Math.round(limitRows)))),
    ),
  );
  return snapshots.docs.map((snapshot) =>
    mapDisputeSlaBreach(snapshot.id, snapshot.data()),
  );
}

export interface TicketEvidenceAssessmentRecord {
  id: string;
  ticketId: string;
  businessName: string;
  customerEmail: string;
  evidenceScore: number;
  confidence: "low" | "medium" | "high";
  riskFlags: string[];
  recommendation: string;
  assessedByUid: string;
  assessedByName: string;
  createdAt: string;
  updatedAt: string;
}

function mapEvidenceAssessment(snapshotId: string, data: Record<string, unknown>) {
  const confidenceRaw = String(data.confidence ?? "low");
  const confidence =
    confidenceRaw === "medium" || confidenceRaw === "high" ? confidenceRaw : "low";
  return {
    id: snapshotId,
    ticketId: String(data.ticketId ?? ""),
    businessName: String(data.businessName ?? ""),
    customerEmail: String(data.customerEmail ?? ""),
    evidenceScore: Number(data.evidenceScore ?? 0),
    confidence,
    riskFlags: Array.isArray(data.riskFlags)
      ? (data.riskFlags as unknown[]).map((entry) => String(entry))
      : [],
    recommendation: String(data.recommendation ?? ""),
    assessedByUid: String(data.assessedByUid ?? ""),
    assessedByName: String(data.assessedByName ?? ""),
    createdAt: toISODate(data.createdAt),
    updatedAt: toISODate(data.updatedAt),
  } satisfies TicketEvidenceAssessmentRecord;
}

export async function analyzeTicketEvidence(payload: {
  ticketId: string;
  adminUid: string;
  adminName: string;
}) {
  const database = getDb();
  const ticketSnapshot = await getDoc(doc(database, "supportTickets", payload.ticketId));
  if (!ticketSnapshot.exists()) throw new Error("Ticket not found.");
  const ticket = mapSupportTicket(ticketSnapshot.id, ticketSnapshot.data());
  const evidenceCount = ticket.evidenceUrls.length;
  const descriptionLength = ticket.description.trim().length;
  const expectedLength = ticket.expectedOutcome.trim().length;
  const keywordSignals = /(invoice|receipt|order|payment|chat|screenshot|video|email)/i.test(
    `${ticket.description} ${ticket.expectedOutcome}`,
  )
    ? 1
    : 0;
  const priorityWeight = ticket.priority === "critical" ? 12 : ticket.priority === "high" ? 8 : 4;
  const evidenceScore = Math.max(
    0,
    Math.min(
      100,
      Math.round(
        evidenceCount * 22 +
          Math.min(24, Math.round(descriptionLength / 8)) +
          Math.min(12, Math.round(expectedLength / 10)) +
          keywordSignals * 8 +
          priorityWeight,
      ),
    ),
  );
  const confidence: TicketEvidenceAssessmentRecord["confidence"] =
    evidenceScore >= 75 ? "high" : evidenceScore >= 45 ? "medium" : "low";
  const riskFlags: string[] = [];
  if (evidenceCount === 0) riskFlags.push("no_evidence_uploaded");
  if (descriptionLength < 40) riskFlags.push("low_context_description");
  if (expectedLength < 12) riskFlags.push("expected_outcome_not_clear");
  if (ticket.priority === "critical" && evidenceCount <= 1) {
    riskFlags.push("critical_without_strong_proof");
  }
  const recommendation =
    confidence === "high"
      ? "Evidence is strong. Proceed to direct mediation and likely resolution."
      : confidence === "medium"
        ? "Request one additional proof artifact before final resolution."
        : "Insufficient evidence. Ask customer for invoice/payment proof and timeline details.";

  const ref = doc(database, "ticketEvidenceAssessments", payload.ticketId);
  await setDoc(
    ref,
    {
      ticketId: ticket.id,
      businessName: ticket.businessName,
      customerEmail: ticket.customerEmail,
      evidenceScore,
      confidence,
      riskFlags,
      recommendation,
      assessedByUid: payload.adminUid,
      assessedByName: payload.adminName,
      createdAt: serverTimestamp(),
      updatedAt: serverTimestamp(),
    },
    { merge: true },
  );
}

export async function fetchTicketEvidenceAssessments(limitRows = 120) {
  const database = getDb();
  const snapshots = await getDocs(
    query(
      collection(database, "ticketEvidenceAssessments"),
      orderBy("updatedAt", "desc"),
      limit(Math.max(1, Math.min(300, Math.round(limitRows)))),
    ),
  );
  return snapshots.docs.map((snapshot) => mapEvidenceAssessment(snapshot.id, snapshot.data()));
}

export interface MerchantRiskProfileRecord {
  id: string;
  businessId: string;
  businessName: string;
  businessSlug: string;
  ownerUid: string;
  totalOrders: number;
  refundedOrders: number;
  refundRatePercent: number;
  openTickets: number;
  riskScore: number;
  riskBand: "low" | "medium" | "high";
  updatedAt: string;
}

function mapMerchantRisk(snapshotId: string, data: Record<string, unknown>) {
  const riskBandRaw = String(data.riskBand ?? "low");
  const riskBand = riskBandRaw === "medium" || riskBandRaw === "high" ? riskBandRaw : "low";
  return {
    id: snapshotId,
    businessId: String(data.businessId ?? ""),
    businessName: String(data.businessName ?? ""),
    businessSlug: String(data.businessSlug ?? ""),
    ownerUid: String(data.ownerUid ?? ""),
    totalOrders: Number(data.totalOrders ?? 0),
    refundedOrders: Number(data.refundedOrders ?? 0),
    refundRatePercent: Number(data.refundRatePercent ?? 0),
    openTickets: Number(data.openTickets ?? 0),
    riskScore: Number(data.riskScore ?? 0),
    riskBand,
    updatedAt: toISODate(data.updatedAt),
  } satisfies MerchantRiskProfileRecord;
}

function determineRiskBand(score: number): MerchantRiskProfileRecord["riskBand"] {
  if (score >= 70) return "high";
  if (score >= 40) return "medium";
  return "low";
}

export async function refreshMerchantRiskProfile(ownerUid: string) {
  const business = await fetchPrimaryBusinessByOwner(ownerUid);
  if (!business) throw new Error("Business not found.");
  const database = getDb();
  const [orderSnapshots, ticketSnapshots] = await Promise.all([
    getDocs(
      query(collection(database, "orders"), where("businessOwnerUid", "==", ownerUid), limit(600)),
    ),
    getDocs(
      query(
        collection(database, "supportTickets"),
        where("participantUids", "array-contains", ownerUid),
        limit(400),
      ),
    ),
  ]);
  const orders = orderSnapshots.docs.map((snapshot) =>
    mapOrder(snapshot.id, snapshot.data() as Record<string, unknown>),
  );
  const tickets = ticketSnapshots.docs.map((snapshot) =>
    mapSupportTicket(snapshot.id, snapshot.data()),
  );
  const totalOrders = orders.length;
  const refundedOrders = orders.filter((row) => row.status === "refunded").length;
  const openTickets = tickets.filter((row) =>
    ["open", "in_discussion", "awaiting_admin"].includes(row.status),
  ).length;
  const refundRatePercent =
    totalOrders > 0 ? Number(((refundedOrders / totalOrders) * 100).toFixed(2)) : 0;
  const ticketRatePercent = totalOrders > 0 ? (openTickets / totalOrders) * 100 : openTickets * 5;
  const riskScore = Math.max(
    0,
    Math.min(100, Math.round(refundRatePercent * 1.6 + ticketRatePercent * 1.3)),
  );
  const riskBand = determineRiskBand(riskScore);
  await setDoc(
    doc(database, "merchantRiskProfiles", business.id),
    {
      businessId: business.id,
      businessName: business.businessName,
      businessSlug: business.slug,
      ownerUid,
      totalOrders,
      refundedOrders,
      refundRatePercent,
      openTickets,
      riskScore,
      riskBand,
      updatedAt: serverTimestamp(),
    },
    { merge: true },
  );
}

export async function fetchMerchantRiskProfiles(limitRows = 200) {
  const database = getDb();
  const snapshots = await getDocs(
    query(
      collection(database, "merchantRiskProfiles"),
      orderBy("updatedAt", "desc"),
      limit(Math.max(1, Math.min(400, Math.round(limitRows)))),
    ),
  );
  return snapshots.docs.map((snapshot) => mapMerchantRisk(snapshot.id, snapshot.data()));
}

export async function refreshAllMerchantRiskProfiles(limitRows = 100) {
  const database = getDb();
  const businesses = await getDocs(
    query(
      collection(database, "businessApplications"),
      where("status", "==", "approved"),
      limit(Math.max(1, Math.min(300, Math.round(limitRows)))),
    ),
  );
  for (const snapshot of businesses.docs) {
    const row = mapBasicBusiness(snapshot.id, snapshot.data());
    if (!row.ownerUid) continue;
    await refreshMerchantRiskProfile(row.ownerUid);
  }
}

export interface ScopedIntegrationApiKeyRecord {
  id: string;
  ownerUid: string;
  businessId: string;
  label: string;
  keyValue: string;
  scopes: string[];
  active: boolean;
  lastUsedAt?: string;
  expiresAt?: string;
  rotatedAt?: string;
  createdAt: string;
  updatedAt: string;
}

function mapApiKey(snapshotId: string, data: Record<string, unknown>) {
  return {
    id: snapshotId,
    ownerUid: String(data.ownerUid ?? ""),
    businessId: String(data.businessId ?? ""),
    label: String(data.label ?? "API key"),
    keyValue: String(data.keyValue ?? ""),
    scopes: Array.isArray(data.scopes)
      ? (data.scopes as unknown[]).map((entry) => String(entry))
      : [],
    active: Boolean(data.active),
    lastUsedAt: data.lastUsedAt ? toISODate(data.lastUsedAt) : undefined,
    expiresAt: data.expiresAt ? String(data.expiresAt) : undefined,
    rotatedAt: data.rotatedAt ? toISODate(data.rotatedAt) : undefined,
    createdAt: toISODate(data.createdAt),
    updatedAt: toISODate(data.updatedAt),
  } satisfies ScopedIntegrationApiKeyRecord;
}

function generateIntegrationApiKey() {
  return `bvk_live_${randomFragment(8)}${randomFragment(8)}${randomFragment(8)}`;
}

export async function createScopedIntegrationApiKey(payload: {
  ownerUid: string;
  label: string;
  scopes: string[];
  expiresAt?: string;
}) {
  const business = await fetchPrimaryBusinessByOwner(payload.ownerUid);
  if (!business) throw new Error("Business profile not found.");
  const database = getDb();
  const keyValue = generateIntegrationApiKey();
  const ref = await addDoc(collection(database, "integrationApiKeys"), {
    ownerUid: payload.ownerUid,
    businessId: business.id,
    label: payload.label.trim() || "API key",
    keyValue,
    scopes: payload.scopes.map((scope) => scope.trim()).filter(Boolean),
    active: true,
    expiresAt: payload.expiresAt?.trim() || null,
    createdAt: serverTimestamp(),
    updatedAt: serverTimestamp(),
  });
  return { id: ref.id, keyValue };
}

export async function fetchScopedIntegrationApiKeys(ownerUid: string, limitRows = 80) {
  const database = getDb();
  const snapshots = await getDocs(
    query(
      collection(database, "integrationApiKeys"),
      where("ownerUid", "==", ownerUid),
      orderBy("updatedAt", "desc"),
      limit(Math.max(1, Math.min(200, Math.round(limitRows)))),
    ),
  );
  return snapshots.docs.map((snapshot) => mapApiKey(snapshot.id, snapshot.data()));
}

export async function rotateScopedIntegrationApiKey(payload: { ownerUid: string; keyId: string }) {
  const database = getDb();
  const ref = doc(database, "integrationApiKeys", payload.keyId);
  const snapshot = await getDoc(ref);
  if (!snapshot.exists()) throw new Error("API key not found.");
  const row = mapApiKey(snapshot.id, snapshot.data());
  if (row.ownerUid !== payload.ownerUid) throw new Error("You cannot rotate this API key.");
  const keyValue = generateIntegrationApiKey();
  await updateDoc(ref, {
    keyValue,
    rotatedAt: serverTimestamp(),
    updatedAt: serverTimestamp(),
  });
  return keyValue;
}

export async function revokeScopedIntegrationApiKey(payload: { ownerUid: string; keyId: string }) {
  const database = getDb();
  const ref = doc(database, "integrationApiKeys", payload.keyId);
  const snapshot = await getDoc(ref);
  if (!snapshot.exists()) return;
  const row = mapApiKey(snapshot.id, snapshot.data());
  if (row.ownerUid !== payload.ownerUid) throw new Error("You cannot revoke this API key.");
  await updateDoc(ref, {
    active: false,
    updatedAt: serverTimestamp(),
  });
}

export interface WidgetConversionDailyRecord {
  dateKey: string;
  impressions: number;
  clicks: number;
  orders: number;
  conversionRatePercent: number;
}

export interface WidgetConversionAnalyticsRecord {
  ownerUid: string;
  businessId: string;
  businessName: string;
  totalImpressions: number;
  totalClicks: number;
  totalOrders: number;
  ctrPercent: number;
  clickToOrderPercent: number;
  daily: WidgetConversionDailyRecord[];
}

export async function fetchWidgetConversionAnalyticsByOwner(ownerUid: string, days = 30) {
  const business = await fetchPrimaryBusinessByOwner(ownerUid);
  if (!business) {
    return null;
  }
  const database = getDb();
  const since = new Date(Date.now() - Math.max(1, days) * 24 * 60 * 60 * 1000);
  const [widgetSnapshots, orderSnapshots] = await Promise.all([
    getDocs(
      query(
        collection(database, "trustBadgeWidgetDailyStats"),
        where("ownerUid", "==", ownerUid),
        orderBy("dateKey", "desc"),
        limit(Math.max(1, days + 7)),
      ),
    ),
    getDocs(
      query(
        collection(database, "orders"),
        where("businessOwnerUid", "==", ownerUid),
        orderBy("createdAt", "desc"),
        limit(700),
      ),
    ),
  ]);
  const orders = orderSnapshots.docs
    .map((snapshot) => mapOrder(snapshot.id, snapshot.data() as Record<string, unknown>))
    .filter((row) => Date.parse(row.createdAt) >= since.getTime());

  const ordersByDate = new Map<string, number>();
  for (const row of orders) {
    const key = row.createdAt.slice(0, 10);
    ordersByDate.set(key, (ordersByDate.get(key) ?? 0) + 1);
  }

  const daily: WidgetConversionDailyRecord[] = widgetSnapshots.docs
    .map((snapshot) => {
      const data = snapshot.data() as Record<string, unknown>;
      const dateKey = String(data.dateKey ?? "");
      const impressions = Number(data.impressions ?? 0);
      const clicks = Number(data.clicks ?? 0);
      const dayOrders = ordersByDate.get(dateKey) ?? 0;
      return {
        dateKey,
        impressions,
        clicks,
        orders: dayOrders,
        conversionRatePercent:
          clicks > 0 ? Number(((dayOrders / clicks) * 100).toFixed(2)) : 0,
      } satisfies WidgetConversionDailyRecord;
    })
    .filter((row) => row.dateKey && Date.parse(`${row.dateKey}T00:00:00.000Z`) >= since.getTime())
    .sort((a, b) => Date.parse(b.dateKey) - Date.parse(a.dateKey));

  const totalImpressions = daily.reduce((sum, row) => sum + row.impressions, 0);
  const totalClicks = daily.reduce((sum, row) => sum + row.clicks, 0);
  const totalOrders = daily.reduce((sum, row) => sum + row.orders, 0);
  const ctrPercent = totalImpressions > 0 ? Number(((totalClicks / totalImpressions) * 100).toFixed(2)) : 0;
  const clickToOrderPercent = totalClicks > 0 ? Number(((totalOrders / totalClicks) * 100).toFixed(2)) : 0;

  const snapshotId = `${business.id}_${new Date().toISOString().slice(0, 7)}`;
  await setDoc(
    doc(database, "widgetConversionSnapshots", snapshotId),
    {
      ownerUid,
      businessId: business.id,
      businessName: business.businessName,
      totalImpressions,
      totalClicks,
      totalOrders,
      ctrPercent,
      clickToOrderPercent,
      updatedAt: serverTimestamp(),
    },
    { merge: true },
  );

  return {
    ownerUid,
    businessId: business.id,
    businessName: business.businessName,
    totalImpressions,
    totalClicks,
    totalOrders,
    ctrPercent,
    clickToOrderPercent,
    daily,
  } satisfies WidgetConversionAnalyticsRecord;
}

export interface CrmLeadRecord {
  id: string;
  ownerUid: string;
  businessId: string;
  name: string;
  email: string;
  source: string;
  status: "new" | "qualified" | "won" | "lost";
  note?: string;
  createdAt: string;
  updatedAt: string;
}

export interface CrmSegmentRecord {
  id: string;
  ownerUid: string;
  businessId: string;
  name: string;
  criteria: string;
  active: boolean;
  updatedAt: string;
}

export interface CrmCampaignRecord {
  id: string;
  ownerUid: string;
  businessId: string;
  title: string;
  message: string;
  targetSegmentId?: string;
  status: "draft" | "scheduled" | "sent";
  createdAt: string;
  updatedAt: string;
}

function mapCrmLead(snapshotId: string, data: Record<string, unknown>) {
  const statusRaw = String(data.status ?? "new");
  const status =
    statusRaw === "qualified" || statusRaw === "won" || statusRaw === "lost"
      ? statusRaw
      : "new";
  return {
    id: snapshotId,
    ownerUid: String(data.ownerUid ?? ""),
    businessId: String(data.businessId ?? ""),
    name: String(data.name ?? ""),
    email: String(data.email ?? ""),
    source: String(data.source ?? "manual"),
    status,
    note: data.note ? String(data.note) : undefined,
    createdAt: toISODate(data.createdAt),
    updatedAt: toISODate(data.updatedAt),
  } satisfies CrmLeadRecord;
}

function mapCrmSegment(snapshotId: string, data: Record<string, unknown>) {
  return {
    id: snapshotId,
    ownerUid: String(data.ownerUid ?? ""),
    businessId: String(data.businessId ?? ""),
    name: String(data.name ?? ""),
    criteria: String(data.criteria ?? ""),
    active: Boolean(data.active),
    updatedAt: toISODate(data.updatedAt),
  } satisfies CrmSegmentRecord;
}

function mapCrmCampaign(snapshotId: string, data: Record<string, unknown>) {
  const statusRaw = String(data.status ?? "draft");
  const status = statusRaw === "scheduled" || statusRaw === "sent" ? statusRaw : "draft";
  return {
    id: snapshotId,
    ownerUid: String(data.ownerUid ?? ""),
    businessId: String(data.businessId ?? ""),
    title: String(data.title ?? ""),
    message: String(data.message ?? ""),
    targetSegmentId: data.targetSegmentId ? String(data.targetSegmentId) : undefined,
    status,
    createdAt: toISODate(data.createdAt),
    updatedAt: toISODate(data.updatedAt),
  } satisfies CrmCampaignRecord;
}

export async function createCrmLead(payload: {
  ownerUid: string;
  name: string;
  email: string;
  source: string;
  note?: string;
}) {
  const business = await fetchPrimaryBusinessByOwner(payload.ownerUid);
  if (!business) throw new Error("Business profile not found.");
  const database = getDb();
  await addDoc(collection(database, "crmLeads"), {
    ownerUid: payload.ownerUid,
    businessId: business.id,
    name: payload.name.trim(),
    email: payload.email.trim().toLowerCase(),
    source: payload.source.trim() || "manual",
    status: "new",
    note: payload.note?.trim() || null,
    createdAt: serverTimestamp(),
    updatedAt: serverTimestamp(),
  });
}

export async function fetchCrmLeadsByOwner(ownerUid: string, limitRows = 200) {
  const database = getDb();
  const snapshots = await getDocs(
    query(
      collection(database, "crmLeads"),
      where("ownerUid", "==", ownerUid),
      orderBy("createdAt", "desc"),
      limit(Math.max(1, Math.min(400, Math.round(limitRows)))),
    ),
  );
  return snapshots.docs.map((snapshot) => mapCrmLead(snapshot.id, snapshot.data()));
}

export async function upsertCrmSegment(payload: {
  ownerUid: string;
  segmentId?: string;
  name: string;
  criteria: string;
  active?: boolean;
}) {
  const business = await fetchPrimaryBusinessByOwner(payload.ownerUid);
  if (!business) throw new Error("Business profile not found.");
  const database = getDb();
  const ref = payload.segmentId?.trim()
    ? doc(database, "crmSegments", payload.segmentId.trim())
    : doc(collection(database, "crmSegments"));
  await setDoc(
    ref,
    {
      ownerUid: payload.ownerUid,
      businessId: business.id,
      name: payload.name.trim(),
      criteria: payload.criteria.trim(),
      active: payload.active ?? true,
      updatedAt: serverTimestamp(),
      createdAt: serverTimestamp(),
    },
    { merge: true },
  );
  return ref.id;
}

export async function fetchCrmSegmentsByOwner(ownerUid: string, limitRows = 80) {
  const database = getDb();
  const snapshots = await getDocs(
    query(
      collection(database, "crmSegments"),
      where("ownerUid", "==", ownerUid),
      orderBy("updatedAt", "desc"),
      limit(Math.max(1, Math.min(200, Math.round(limitRows)))),
    ),
  );
  return snapshots.docs.map((snapshot) => mapCrmSegment(snapshot.id, snapshot.data()));
}

export async function createCrmCampaign(payload: {
  ownerUid: string;
  title: string;
  message: string;
  targetSegmentId?: string;
  status?: "draft" | "scheduled" | "sent";
}) {
  const business = await fetchPrimaryBusinessByOwner(payload.ownerUid);
  if (!business) throw new Error("Business profile not found.");
  const database = getDb();
  await addDoc(collection(database, "crmCampaigns"), {
    ownerUid: payload.ownerUid,
    businessId: business.id,
    title: payload.title.trim(),
    message: payload.message.trim(),
    targetSegmentId: payload.targetSegmentId?.trim() || null,
    status: payload.status ?? "draft",
    createdAt: serverTimestamp(),
    updatedAt: serverTimestamp(),
  });
}

export async function fetchCrmCampaignsByOwner(ownerUid: string, limitRows = 120) {
  const database = getDb();
  const snapshots = await getDocs(
    query(
      collection(database, "crmCampaigns"),
      where("ownerUid", "==", ownerUid),
      orderBy("createdAt", "desc"),
      limit(Math.max(1, Math.min(300, Math.round(limitRows)))),
    ),
  );
  return snapshots.docs.map((snapshot) => mapCrmCampaign(snapshot.id, snapshot.data()));
}

export interface ReferralProgramRecord {
  id: string;
  ownerUid: string;
  businessId: string;
  active: boolean;
  commissionPercent: number;
  signupBonusInr: number;
  updatedAt: string;
}

export interface ReferralInviteRecord {
  id: string;
  ownerUid: string;
  businessId: string;
  code: string;
  inviteeEmail: string;
  status: "pending" | "joined" | "rewarded";
  createdAt: string;
  updatedAt: string;
}

function mapReferralProgram(snapshotId: string, data: Record<string, unknown>) {
  return {
    id: snapshotId,
    ownerUid: String(data.ownerUid ?? ""),
    businessId: String(data.businessId ?? ""),
    active: Boolean(data.active),
    commissionPercent: Number(data.commissionPercent ?? 0),
    signupBonusInr: Number(data.signupBonusInr ?? 0),
    updatedAt: toISODate(data.updatedAt),
  } satisfies ReferralProgramRecord;
}

function mapReferralInvite(snapshotId: string, data: Record<string, unknown>) {
  const rawStatus = String(data.status ?? "pending");
  const status = rawStatus === "joined" || rawStatus === "rewarded" ? rawStatus : "pending";
  return {
    id: snapshotId,
    ownerUid: String(data.ownerUid ?? ""),
    businessId: String(data.businessId ?? ""),
    code: String(data.code ?? ""),
    inviteeEmail: String(data.inviteeEmail ?? ""),
    status,
    createdAt: toISODate(data.createdAt),
    updatedAt: toISODate(data.updatedAt),
  } satisfies ReferralInviteRecord;
}

export async function upsertReferralProgram(payload: {
  ownerUid: string;
  active: boolean;
  commissionPercent: number;
  signupBonusInr: number;
}) {
  const business = await fetchPrimaryBusinessByOwner(payload.ownerUid);
  if (!business) throw new Error("Business profile not found.");
  const database = getDb();
  await setDoc(
    doc(database, "referralPrograms", payload.ownerUid),
    {
      ownerUid: payload.ownerUid,
      businessId: business.id,
      active: payload.active,
      commissionPercent: Math.max(0, Number(payload.commissionPercent ?? 0)),
      signupBonusInr: Math.max(0, Number(payload.signupBonusInr ?? 0)),
      updatedAt: serverTimestamp(),
      createdAt: serverTimestamp(),
    },
    { merge: true },
  );
}

export async function fetchReferralProgramByOwner(ownerUid: string) {
  const database = getDb();
  const snapshot = await getDoc(doc(database, "referralPrograms", ownerUid));
  return snapshot.exists()
    ? mapReferralProgram(snapshot.id, snapshot.data() as Record<string, unknown>)
    : null;
}

export async function createReferralInvite(payload: { ownerUid: string; inviteeEmail: string }) {
  const business = await fetchPrimaryBusinessByOwner(payload.ownerUid);
  if (!business) throw new Error("Business profile not found.");
  const database = getDb();
  const code = `REF-${randomFragment(4).toUpperCase()}-${randomFragment(4).toUpperCase()}`;
  await addDoc(collection(database, "referralInvites"), {
    ownerUid: payload.ownerUid,
    businessId: business.id,
    code,
    inviteeEmail: payload.inviteeEmail.trim().toLowerCase(),
    status: "pending",
    createdAt: serverTimestamp(),
    updatedAt: serverTimestamp(),
  });
  return code;
}

export async function fetchReferralInvitesByOwner(ownerUid: string, limitRows = 120) {
  const database = getDb();
  const snapshots = await getDocs(
    query(
      collection(database, "referralInvites"),
      where("ownerUid", "==", ownerUid),
      orderBy("createdAt", "desc"),
      limit(Math.max(1, Math.min(300, Math.round(limitRows)))),
    ),
  );
  return snapshots.docs.map((snapshot) => mapReferralInvite(snapshot.id, snapshot.data()));
}

export interface ComplianceProfileRecord {
  id: string;
  ownerUid: string;
  businessId: string;
  countryCode: string;
  businessType: string;
  kycStatus: "pending" | "submitted" | "verified" | "rejected";
  kybStatus: "pending" | "submitted" | "verified" | "rejected";
  notes?: string;
  updatedAt: string;
}

export interface ComplianceDocumentRecord {
  id: string;
  ownerUid: string;
  businessId: string;
  title: string;
  documentType: string;
  url: string;
  status: "submitted" | "verified" | "rejected";
  uploadedAt: string;
}

function mapComplianceProfile(snapshotId: string, data: Record<string, unknown>) {
  const normalizeStatus = (value: unknown) => {
    const raw = String(value ?? "pending");
    return raw === "submitted" || raw === "verified" || raw === "rejected"
      ? raw
      : "pending";
  };
  return {
    id: snapshotId,
    ownerUid: String(data.ownerUid ?? ""),
    businessId: String(data.businessId ?? ""),
    countryCode: String(data.countryCode ?? ""),
    businessType: String(data.businessType ?? ""),
    kycStatus: normalizeStatus(data.kycStatus),
    kybStatus: normalizeStatus(data.kybStatus),
    notes: data.notes ? String(data.notes) : undefined,
    updatedAt: toISODate(data.updatedAt),
  } satisfies ComplianceProfileRecord;
}

function mapComplianceDocument(snapshotId: string, data: Record<string, unknown>) {
  const rawStatus = String(data.status ?? "submitted");
  const status = rawStatus === "verified" || rawStatus === "rejected" ? rawStatus : "submitted";
  return {
    id: snapshotId,
    ownerUid: String(data.ownerUid ?? ""),
    businessId: String(data.businessId ?? ""),
    title: String(data.title ?? ""),
    documentType: String(data.documentType ?? ""),
    url: String(data.url ?? ""),
    status,
    uploadedAt: toISODate(data.uploadedAt ?? data.createdAt),
  } satisfies ComplianceDocumentRecord;
}

export async function upsertComplianceProfile(payload: {
  ownerUid: string;
  countryCode: string;
  businessType: string;
  kycStatus: ComplianceProfileRecord["kycStatus"];
  kybStatus: ComplianceProfileRecord["kybStatus"];
  notes?: string;
}) {
  const business = await fetchPrimaryBusinessByOwner(payload.ownerUid);
  if (!business) throw new Error("Business profile not found.");
  const database = getDb();
  await setDoc(
    doc(database, "complianceProfiles", payload.ownerUid),
    {
      ownerUid: payload.ownerUid,
      businessId: business.id,
      countryCode: payload.countryCode.trim().toUpperCase(),
      businessType: payload.businessType.trim(),
      kycStatus: payload.kycStatus,
      kybStatus: payload.kybStatus,
      notes: payload.notes?.trim() || null,
      updatedAt: serverTimestamp(),
      createdAt: serverTimestamp(),
    },
    { merge: true },
  );
}

export async function fetchComplianceProfileByOwner(ownerUid: string) {
  const database = getDb();
  const snapshot = await getDoc(doc(database, "complianceProfiles", ownerUid));
  return snapshot.exists()
    ? mapComplianceProfile(snapshot.id, snapshot.data() as Record<string, unknown>)
    : null;
}

export async function addComplianceDocument(payload: {
  ownerUid: string;
  title: string;
  documentType: string;
  url: string;
}) {
  const business = await fetchPrimaryBusinessByOwner(payload.ownerUid);
  if (!business) throw new Error("Business profile not found.");
  const database = getDb();
  await addDoc(collection(database, "complianceDocuments"), {
    ownerUid: payload.ownerUid,
    businessId: business.id,
    title: payload.title.trim(),
    documentType: payload.documentType.trim() || "general",
    url: payload.url.trim(),
    status: "submitted",
    uploadedAt: serverTimestamp(),
    createdAt: serverTimestamp(),
    updatedAt: serverTimestamp(),
  });
}

export async function fetchComplianceDocumentsByOwner(ownerUid: string, limitRows = 120) {
  const database = getDb();
  const snapshots = await getDocs(
    query(
      collection(database, "complianceDocuments"),
      where("ownerUid", "==", ownerUid),
      orderBy("uploadedAt", "desc"),
      limit(Math.max(1, Math.min(300, Math.round(limitRows)))),
    ),
  );
  return snapshots.docs.map((snapshot) =>
    mapComplianceDocument(snapshot.id, snapshot.data()),
  );
}
